name: chatgpt_api_dart
description: Dart client for the unofficial ChatGPT API.

version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  json_annotation: ^4.7.0
  http: ^0.13.5
  uuid: ^3.0.7

dev_dependencies:
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  test: ^1.17.0